=== LucasMAlc/GDSE/src/Tarefa7-GDSE/DTD.dtd
<!DOCTYPE db [
<!ELEMENT db (pessoa+)>
<!ELEMENT pessoa (nome, idade, email+, telefone?)>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT idade (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT telefone (#PCDATA)>
]>

=== LucasMAlc/GDSE/src/Tarefa7-GDSE/xml_modificado.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE db SYSTEM "DTD.dtd">
<db>
  <pessoa>
    <nome> Pedro Maia</nome>
    <idade>33</idade>
    <email>maia@yahoo.com</email>
  </pessoa>
  <pessoa>
    <nome> Ana Maria</nome>
    <idade>24</idade>
    <email>ana.maria@uol.com.br</email>
    <email>ana.maria@yahoo.com.br</email>
    <telefone>3322-4433</telefone>
  </pessoa>
</db>
